#!/bin/sh

# Define global variables

# rescue_shell() - Starts a rescue shell
rescue_shell()
{
	echo 'Dropping you into a shell'
	exec /bin/sh
}

# kecho() - Print a message to kernel log and to stderr
kecho()
{
	echo "initramfs:" "$@" 1>/dev/kmsg
	echo "$@" 1>&2
}

# die() - Fatal error, cannot continue
die()
{
	kecho "FATAL:" "$@"
	rescue_shell
}

# error() - Non fatal error, enable maintenance mode
error()
{
	kecho "ERROR:" "$@"
	MAINTENANCE=true
}

# maintenance() - Starts maintenance shell
maintenance()
{
	echo 'Going into maintenance'
	rescue_shell
}


# Initialization
echo 'INITRAMFS: Start'
test $$ -eq 1 || die "/init expects to be run as PID 1, current PID is $$"

# Load system layout
echo 'Loading system layout'
mount -t proc none /proc || die 'Failed to mount /proc'
mount -t sysfs none /sys || die 'Failed to mount /sys'
mount -t devtmpfs none /dev || die 'Failed to mount /dev'
echo 2 >/proc/sys/kernel/printk

# Load keyboard
echo 'Loading keyboard'
[ -f '${init_keymap}' ] || die 'Keymap ${init_keymap}: file not found'
loadkmap <'${init_keymap}' || die 'Failed to load keymap'
setleds -D +num || die "Failed to enable numlock"

# Parse command line
echo 'Reading cmdline'
for cmdline in $(cat /proc/cmdline); do
	case "${cmdline}" in
	rescue_shell)
		echo 'Manual rescue shell enabled'
		rescue_shell
		;;
	maintenance)
		echo 'Maintenance mode enabled'
		MAINTENANCE=y
		;;
	init=*)
		INIT="${cmdline#*=}"
		echo "Override init with ${INIT}"
		;;
	esac
done

# Unlock LUKS
echo 'Unlocking LUKS partition'
cryptsetup luksOpen --header '${init_luks_header}' '${init_luks_key}' 'key' || die 'Failed to unlock LUKS key'
cryptsetup luksOpen --allow-discards --key-file '/dev/mapper/key' "$(findfs '${init_luks_uuid}')" 'luks' || die 'Failed to unlock LUKS partition'
cryptsetup luksClose 'key' || die 'Failed to close LUKS key'

# Load LVM
echo 'Loading LVM'
lvm lvchange --sysinit -a y 'gentoo/root' || die 'Failed to activate gentoo/root LV'
if [ -z "${MAINTENANCE}" ]; then
	lvm lvchange --sysinit -a y 'gentoo/usr' || die 'Failed to activate gentoo/usr LV'
fi

# Mount ROOT filesystem


